language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. 
  - make
  - cd ..
  - ./run_test.sh
  - cd build
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
