language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - pip install --user cpp-coveralls

script:
  - ls
  - cmake --version
  - mkdir build
  - cd build
  - ls ..
  - cmake .. 
  - make

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/server/.*.cpp.*"

notifications:
  email: false
