language:
  - cpp

install:
  - sudo pip install cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - ./run_test.sh
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
